### ISSUE TITLE
Sample Cloudflared defaul.yaml

### ISSUE THREAD

**Issue by mitchross** [Woll0r/k8s-cluster#1597]
Can you show me an example file for default.yaml

https://github.com/Woll0r/k8s-cluster/blob/main/cluster/apps/networking/cloudflared/secret.enc.yaml

I'd like to deploy cloudflared, but Im unsure the values for default.yaml

**Comment by Woll0r** [comment]
It's a standard Cloudflare tunnel config, similar to the yaml file created by `cloudflared tunnel create k8s-tunnel`

So if you create a tunnel with that command, you can almost one-for-one put the yaml and json it creates into a secret to make it work.

default.yaml
```yaml
tunnel: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
credentials-file: /etc/cloudflared/cred.json
ingress:
- service: http://ingress-nginx-controller.networking
```
cred.json
```json
{
  "AccountTag": "longstringoftext",
  "TunnelSecret": "evenlongerstringoftext",
  "TunnelID": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
  "TunnelName": "k8s-tunnel"
}
```
